"""Prompt construction for Gemini AI analysis."""

import json


MEDICAL_DISCLAIMER = (
    "⚕️ DISCLAIMER: This analysis is generated by an AI system for educational and informational purposes only. "
    "It is NOT a substitute for professional medical advice, diagnosis, or treatment. Always consult a qualified "
    "healthcare professional for medical decisions. Never disregard professional medical advice or delay seeking "
    "it because of information provided by this application."
)


def build_report_analysis_prompt(
    extracted_text: str,
    biomarkers: dict,
    health_metrics: dict,
    user_profile: dict,
    previous_reports: list | None = None,
) -> str:
    """Build a comprehensive prompt for medical report analysis."""

    prompt = f"""You are a professional health analyst AI. Analyze the following medical report data and provide a comprehensive health analysis.

## User Profile
- Age: {user_profile.get('age', 'Not provided')}
- Gender: {user_profile.get('gender', 'Not provided')}
- Height: {user_profile.get('height_cm', 'Not provided')} cm
- Weight: {user_profile.get('weight_kg', 'Not provided')} kg
- Activity Level: {user_profile.get('activity_level', 'Not provided')}
- Health Conditions: {user_profile.get('health_conditions', 'None reported')}
- Allergies: {user_profile.get('allergies', 'None reported')}
- Dietary Preferences: {user_profile.get('dietary_preferences', 'None')}

## Pre-Calculated Health Metrics (computed by the application, DO NOT recalculate)
{json.dumps(health_metrics, indent=2)}

## Extracted Biomarker Values from Lab Report
{json.dumps(biomarkers, indent=2)}

## Raw Report Text (OCR Extracted)
{extracted_text[:3000]}

"""

    if previous_reports:
        prompt += """## Previous Report Data (for trend analysis)
"""
        for prev in previous_reports[-3:]:  # Last 3 reports
            prompt += f"""
### Report from {prev.get('date', 'Unknown')}
Biomarkers: {json.dumps(prev.get('biomarkers', {}), indent=2)}
Previous Scores: Overall={prev.get('overall_score', 'N/A')}
"""

    prompt += """
## INSTRUCTIONS
Analyze the above data and return a JSON response with EXACTLY this structure:

{
  "summary": "A 3-5 sentence overall health summary in simple, encouraging language",

  "scores": {
    "overall": {"score": 0-100, "explanation": "Why this score"},
    "nutrition": {"score": 0-100, "explanation": "Why this score"},
    "fitness": {"score": 0-100, "explanation": "Why this score"},
    "sleep": {"score": 0-100, "explanation": "Why this score"},
    "hydration": {"score": 0-100, "explanation": "Why this score"},
    "mental_wellness": {"score": 0-100, "explanation": "Why this score"},
    "heart_health": {"score": 0-100, "explanation": "Why this score"},
    "lifestyle": {"score": 0-100, "explanation": "Why this score"},
    "risk_assessment": {"score": 0-100, "explanation": "Higher = more risk. Why this score"}
  },

  "abnormal_values": [
    {
      "name": "Biomarker Name",
      "value": "current value with unit",
      "status": "high/low/borderline",
      "normal_range": "reference range",
      "explanation": "Simple language explanation of what this means",
      "possible_causes": ["cause1", "cause2"],
      "health_risks": ["risk1", "risk2"],
      "recommendations": ["action1", "action2"]
    }
  ],

  "recommendations": {
    "dos": ["Do this", "Do that"],
    "donts": ["Avoid this", "Avoid that"],
    "foods_to_eat": [{"name": "Food name", "benefit": "Why eat it", "portion": "Recommended portion"}],
    "foods_to_avoid": [{"name": "Food name", "reason": "Why avoid it"}],
    "healthier_alternatives": [{"instead_of": "Bad food", "try": "Good food", "reason": "Why"}],
    "meal_timing": ["Tip 1", "Tip 2"],
    "daily_meal_plan": {
      "breakfast": {"meal": "description", "calories": 000},
      "mid_morning_snack": {"meal": "description", "calories": 000},
      "lunch": {"meal": "description", "calories": 000},
      "evening_snack": {"meal": "description", "calories": 000},
      "dinner": {"meal": "description", "calories": 000}
    },
    "weekly_highlights": ["Monday focus", "Wednesday focus", "Friday focus"]
  },

  "workout_plan": {
    "walking": {"goal": "X steps/day or X minutes", "frequency": "daily"},
    "cardio": {"exercises": ["exercise1"], "duration": "X minutes", "frequency": "X times/week"},
    "strength": {"exercises": ["exercise1"], "duration": "X minutes", "frequency": "X times/week"},
    "stretching": {"exercises": ["stretch1"], "duration": "X minutes", "frequency": "daily"},
    "yoga": {"poses": ["pose1"], "duration": "X minutes", "frequency": "X times/week"}
  },

  "lifestyle_advice": {
    "sleep_schedule": {"bedtime": "XX:XX PM", "wake_time": "XX:XX AM", "tips": ["tip1"]},
    "morning_routine": ["Step 1", "Step 2"],
    "night_routine": ["Step 1", "Step 2"],
    "stress_management": ["Technique 1", "Technique 2"],
    "meditation": {"type": "Type of meditation", "duration": "X minutes", "frequency": "daily"},
    "hydration_goals": {"daily_target": "X liters", "tips": ["tip1"]},
    "healthy_habits": ["Habit 1", "Habit 2"]
  },

  "trend_analysis": "If previous reports are available, describe improvements/declines and future predictions. Otherwise say 'First report - no trends available yet.'"
}

IMPORTANT RULES:
1. Use simple, non-medical language that anyone can understand
2. Be encouraging but honest about health concerns
3. Base all analysis on the actual biomarker values and health metrics provided
4. Every score must be between 0 and 100
5. Provide specific, actionable recommendations
6. Consider the user's age, gender, activity level, and health conditions
7. Return ONLY valid JSON — no markdown, no code fences, no extra text
"""

    return prompt


def build_food_analysis_prompt() -> str:
    """Build a prompt for food image analysis."""
    return """Analyze this food image and provide a detailed nutritional breakdown.

Return a JSON response with this structure:
{
  "identified_foods": [
    {"name": "Food item", "estimated_quantity": "amount"}
  ],
  "nutrition": {
    "total_calories": 000,
    "protein_g": 00,
    "carbohydrates_g": 00,
    "fats_g": 00,
    "fiber_g": 00,
    "sugar_g": 00,
    "vitamins": ["Vitamin A", "Vitamin C"],
    "minerals": ["Iron", "Calcium"]
  },
  "is_healthy": true/false,
  "verdict": "Explanation of whether this meal is healthy and why",
  "healthier_alternatives": [
    {"instead_of": "current item", "try": "healthier option", "reason": "why it's better"}
  ],
  "meal_score": 0-100,
  "tips": ["Tip 1 for improving this meal"]
}

Return ONLY valid JSON — no markdown, no code fences, no extra text.
"""


def build_comparison_prompt(report1_data: dict, report2_data: dict) -> str:
    """Build a prompt for comparing two reports."""
    return f"""Compare these two medical reports and provide insights about health changes over time.

## Earlier Report
Date: {report1_data.get('date', 'Unknown')}
Biomarkers: {json.dumps(report1_data.get('biomarkers', {}), indent=2)}
Scores: {json.dumps(report1_data.get('scores', {}), indent=2)}

## Latest Report
Date: {report2_data.get('date', 'Unknown')}
Biomarkers: {json.dumps(report2_data.get('biomarkers', {}), indent=2)}
Scores: {json.dumps(report2_data.get('scores', {}), indent=2)}

Return a JSON response:
{{
  "overall_trend": "improving/declining/stable",
  "summary": "2-3 sentence summary of changes",
  "improvements": [{{"biomarker": "name", "change": "old → new", "explanation": "what this means"}}],
  "declines": [{{"biomarker": "name", "change": "old → new", "explanation": "what this means", "action": "what to do"}}],
  "stable": [{{"biomarker": "name", "value": "current"}}],
  "predictions": ["Based on trends, prediction 1"],
  "preventive_actions": ["Action 1 to prevent worsening"]
}}

Return ONLY valid JSON.
"""
